# INS : 동물보호소에 들어온 
# OUTS : 동물보호소에서 입양 보낸
SELECT ANIMAL_INS.NAME, ANIMAL_INS.DATETIME
FROM ANIMAL_INS
LEFT JOIN ANIMAL_OUTS USING(ANIMAL_ID)
WHERE ANIMAL_OUTS.ANIMAL_ID IS NULL AND ANIMAL_INS.ANIMAL_ID IS NOT NULL
ORDER BY ANIMAL_INS.DATETIME ASC
LIMIT 3;