-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/", U.BOARD_ID, "/", FILE_ID, FILE_NAME ,FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD B
RIGHT JOIN USED_GOODS_FILE U
ON B.BOARD_ID = U.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC;